version: "3.8"

services:
  backend:
    image: christianfh08/sistema-de-transferencias-bancarias-backend:latest
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: ${MONGO_URI}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      PORT: 3000
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  frontend:
    image: christianfh08/sistema-de-transferencias-bancarias-frontend:latest
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s